apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ms
  namespace: microservice
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-ms
                port:
                  number: 80
